### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by dfang** [documentcloud/docsplit#133]
i run this command `docsplit images ./jordan.ppt --size 1000x --format jpg -o output` on mac, it works perfect，but not on my ubuntu box 14.04 LTS.

here is the link for [jordan.ppt](http://cl.ly/254034081p3w)

**Comment by knowtheory** [comment]
Hi @dfang,

ubuntu requires that you install some fonts in order to support CJK glyphs.  These are the fonts that we use: https://github.com/documentcloud/documentcloud/blob/f60f3e3b28b537d5ff5527186e16aefdca16bc09/config/server/scripts/setup_common_dependencies.sh#L90-L95

also see the discussions in #95 and #122
